### PR TITLE
bind invokeAPI name

### PR DESCRIPTION
**Pull request by anserwaseem**
## Issue ticket number and link

Closes #

## Checklist before requesting a review

- [x] I have performed a self-review of my code
- [ ] I have added tests
- [x] I have added a changeset `pnpm changeset add`
- [x] I have added example usage in the kitchen sink app

### CODE REVIEW

**Review by sibteali786 — APPROVED** [review]

**Review by evshi — CHANGES_REQUESTED** [review]
You don't need to bind anything to invokeAPI in the code context since it's all javascript already

**Review by evshi — COMMENTED** [review]
@anserwaseem what is the use case for this? This can create issues with how we create our dependencies since the API name is no longer static. Is this something that flutter supports?

**Comment by anserwaseem** [comment]
@evshi Yes flutter side supports this.

https://github.com/EnsembleUI/ensemble-react/assets/32386713/5841a732-e09a-48e1-9b5a-edc0a9fb0e80

No particular use case for now, i just wanted not to write the same widget again (or use Conditional) just because the api name is different.

**Comment by evshi** [comment]
I see - this will require some special handling. The way our bindings work today we analyze the expressions for the symbols that will become dependencies. invokeAPI.name is just a string. We will need to add handling that if the output of the expression is also a symbol then we need to be dependent on that symbol also.

**Review by evshi — APPROVED** [review]
This is probably fine for your use case and it won't break anything.

**Pull request merged**
