### PR TITLE
fix: ensemble storage overwritten issue fix

### LINKED ISSUE #467: Successive writes to storage overwrites previous keys
**Describe the bug**
When using scripts in quick succession, like onLoad for custom widgets in the same parent container, the scripts will overwrite storage.

**To Reproduce**

https://github.com/atlas-health/atlas-navigator-ui/pull/189/files

1. Create two custom widgets
2. Add onLoad scripts to both that set some key in storage
3. Add to same parent container
4. See first key is not set in storage

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

### PR DESCRIPTION
**Pull request by sagardspeed2**
## Describe your changes
successive write to ensemble storage overwritten previous keys

## Issue ticket number and link

Closes #467 

## Checklist before requesting a review

- [ ] I have performed a self-review of my code
- [ ] I have added tests
- [ ] I have added a changeset `pnpm changeset add`
- [ ] I have added example usage in the kitchen sink app

### CODE REVIEW

**Comment by sagardspeed2** [comment]
@evshi I removed the storageBuffer from ensemble storage that fix the issue, but now when we move one screen to another screen, the ensemble storage is not getting reset, and I think that is not an issue. because we are storing the data in session storage which persist on same domain

**Comment by evshi** [comment]
@anserwaseem @sibteali786 can you help @sagardspeed2 test these changes against the latest version of the atlas app.

**Comment by evshi** [comment]
@sagardspeed2 please plan to find a time to validate this fix

**Comment by evshi** [comment]
@sagardspeed2 what is the status here?

**Comment by evshi** [comment]
@sagardspeed2 this issue still occurs if you have storage mutations inside a custom widget onLoad

**Pull request closed without merging**
