### PR TITLE
remove footer static height constraint

### LINKED ISSUE #339: Support footer of any size
Currently the footer component is assumed to be 56 px tall and the rest of the page is sized accordingly. This is an artificial restriction. Technically the footer can be of any height and the page can just "fold underneath" it. In other words, the footer is stacked on top of the page and the page is free to scroll under it

### PR DESCRIPTION
**Pull request by sagardspeed2**
## Describe your changes
Remove fixed height from the footer.

### Screenshots [Optional]
https://github.com/EnsembleUI/ensemble-react/assets/31651612/865259d7-5eac-4024-bdee-ada44e3ce451

## Issue ticket number and link

Closes #
closes #339

## Checklist before requesting a review

- [x] I have performed a self-review of my code
- [ ] I have added tests
- [ ] I have added a changeset `pnpm changeset add`
- [x] I have added example usage in the kitchen sink app

### CODE REVIEW

**Review by evshi — COMMENTED** [review]
Can you also double check this doesn't break the modal screen use case? @anserwaseem PTAL

**Comment by sagardspeed2** [comment]
@evshi I tested this one for modal screen behaviour. 
Here is the screen recording for that

https://we.tl/t-8lpGbE0Qok

**Comment by anserwaseem** [comment]
@sagardspeed2 can we also support footer when using useNavigateModal, see currently footer is not working:

image

**Review by anserwaseem — APPROVED** [review]
LGTM

**Review by evshi — APPROVED** [review]

**Pull request merged**
